### PR TITLE
Responsive design

### PR DESCRIPTION
**Pull request by adamclasic**
## Responsive Design
This project consists of replicating The Next Web website putting emphasis on how it behaves differently depending on the size of the screen where the website is rendered.

-Worked with media queries to resize according to different screen sizes
-Create differently Headers for different screens

[Live Version](https://rawcdn.githack.com/adamclasic/Building-with-Responsive-Design/ec639e77430a82baff9a94ba0591802260ab07d9/index.html)

### CODE REVIEW

**Comment by thsvr** [comment]
Project under review by Thaís Vieira.

**Comment by thsvr** [comment]
### **Status: Changes required**


Hi @adamclasic and @Morrism1 :smile: :smile: 


Your job looks amazing and you guys are almost done, so I will show a few changes required that are not done yet, so please read it carefully and do the changes before submit it again. :+1: 


### **Small screen:** 

navbar: Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to search icon), so please hidden the list on the top navbar on your project: 

navbar1



General:

:v:  Please enable the stickler in your repo before submitting the project and fix the changes, if there are some required;

:v:  You guys have to use the same pull request to submit the project when it is required for other reviews, so please open just one pull request for the next projects and use it until get the project approved.

If you have any questions, don't hesitate to contact me through slack [@Thaís Vieira Azevedo](url)

Happy coding  :computer:  and good luck on the next review :+1: 

Thaís Vieira (TSE)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review by Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Nice work @adamclasic and @Morrism1!
You have done well in building this and attending to the changes requested by @thsvr :clap: Please note, that there are still a few changes required of you, and consider my comments below.

#### Missing breakpoint
Please consider for a moment, the original website between 768px and 425px, you may find that what happens with the positioning, sizing and general apprearance of the elements on the page differs from yours. That being said, please take into account that one major breakpoint is missing from your project as you have 2 instead of 3 handled. Make the required changes before your next review :+1: 
screenshot

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by adamclasic** [comment]
@Oluwadamilareolusakin It's obvious that you didn't read the code nor review the page.
there are 4 breaking points in the code and not 2 as you said.
for the horizontal scroll, it's nowhere to be found.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### Good job so far :clap: However, you an issue to work o before your project could be approved.
- On mobile devices, your logo disappears, add it.
logo

### Make the change and resubmit for another review. Good luck.
- Happy coding!

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### Good job you have done :clap: Having verified you made all the required changes from the previous reviews. Your project looks good and passes the requirements, therefore, I approve of it. Congratulations :boom: :100:
### You can now merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
